DIYBlog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/blog/')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Serving Static files in dev
# Apparently we need to add this but not as a part of the list? Maybe static()
# does something weird? Definitely should keep it separate either way, as this
# should be removed when moving into production
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from blog.views import BlogHome, PostDetail, AuthorDetail, AuthorPosts
from blog.views import AuthorList, CreatePost, CreateComment, UpdateAuthor
from blog.views import UpdatePost


urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('post/<int:pk>/', PostDetail.as_view(), name='post-detail'),
    path('author/<int:pk>/', AuthorDetail.as_view(), name='author-detail'),
    path('posts/author/<int:pk>/', AuthorPosts.as_view(), name='author-posts'),
    path('authors/', AuthorList.as_view(), name='author-list'),
    path('post/create/', CreatePost.as_view(), name='create-post'),
    path('post/<int:pk>/comment/', CreateComment.as_view(),
         name='create-comment'),
    path('author/<int:pk>/update/', UpdateAuthor.as_view(),
         name='update-author'),
    path('post/<int:pk>/update/', UpdatePost.as_view(), name='update-post'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
import datetime


class Author(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    headshot = models.ImageField(null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        if self.name:
            return self.name
        else:
            return self.user.username

    def get_absolute_url(self):
        return reverse('author-detail', kwargs={'pk': self.id})


class Post(models.Model):

    title = models.CharField(max_length=200)
    text = models.TextField()
    author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL)
    published = models.DateTimeField(verbose_name="publish date/time",
                                     default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def is_published(self):
        "Returns False if 'published' is in future"
        return self.published <= timezone.now()

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.id})

    class Meta:
        ordering = ['-published']


class Comment(models.Model):

    title = models.CharField(max_length=100)
    text = models.TextField(max_length=2000)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    last_modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def was_modified(self):
        return self.last_modified - self.created > datetime.timedelta(
            seconds=.4)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.post.id})

    class Meta:
        ordering = ['created']

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils import timezone
from blog.models import Post, Author, Comment


class BlogHome(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(published__lte=timezone.now())


class PostDetail(DetailView):
    model = Post


class AuthorDetail(DetailView):
    model = Author


class AuthorPosts(DetailView):
    model = Author
    template_name = 'blog/post_list.html'


class AuthorList(ListView):
    model = Author


class CreatePost(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'text', 'published']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = Author.objects.get(user=self.request.user)
        post.save()
        return super().form_valid(form)


class CreateComment(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['title', 'text']

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.post = Post.objects.get(pk=self.kwargs['pk'])
        comment.save()
        return super().form_valid(form)


class UpdateAuthor(UserPassesTestMixin, UpdateView):
    model = Author
    fields = ['bio', 'headshot']

    def test_func(self):
        try:
            return self.request.user.author.pk == self.kwargs['pk']
        except AttributeError:
            return False


class UpdatePost(UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'text', 'published']

    def test_func(self):
        try:
            return self.request.user.author.id == Post.objects.get(
                pk=self.kwargs['pk']).author.id
        except AttributeError:
            return False

blog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block title %}<title>My Basic Blog</title>{% endblock %}
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>

    {% load static %}
    <link rel='stylesheet' href='{% static 'css/primitive/main.css' %}'>

  </head>
  <body>
    <header>
      <div class="container">
        <div class="page-header">
          <h1><a href="{% url 'home' %}">My Blog Title</a></h1>
      </div>
    </header>
    <div class='container-fluid'>

      <div class='row'>
	<div class='col-sm-2'>
	  {% block sidebar %}
	  <ul class='sidebar-nav'>
	    <li><a href='{% url "home" %}'>Home</a></li>
            <li><a href="{% url 'author-list' %}">Authors</a></li>
            <hr>
            {% if user.is_authenticated %}
            {% if user.author %}
            <li><a href="{% url 'author-detail' user.author.id %}">Your profile</a></li>
            <li><a href="{% url 'author-posts' user.author.id %}">Your Posts</a></li>
            {% endif %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
	  </ul>
	  {% endblock %}
	</div>
	<div class='col-sm-10'>
	  {% block content %}{% endblock %}
	  {% block pagination %}
	  {% if is_paginated %}
	  <div class='pagination'>
	    <span class='page-links'>
	      {% if page_obj.has_previous %}
	      <a href='{{ request.path }}?page={{ page_obj.previous_page_number }}'>&lt;&lt;</a>
	      {% endif %}
	      {% for num in page_obj.paginator.page_range %}
	      {% if forloop.counter != page_obj.number %}<a href='{{ request.path }}?page={{ num }}'>{% endif %}
		{{ num }}
		{% if forloop.counter != page_obj.number %}</a>{% endif %}
	      {% endfor %}
	      {% if page_obj.has_next %}
	      <a href='{{ request.path }}?page={{ page_obj.next_page_number }}'>&gt;&gt;</a>
	      {% endif %}
	    </span>
	  </div>
	  {% endif %}
	  {% endblock %}
	</div>
      </div>
    </div>

  </body>
</html>

blog/templates/blog/author_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ author }}</h1>
<p>{{ author.bio }}</p>
<p><a href="{% url 'author-posts' author.pk %}">Click here</a> to see posts by {{ author }}.</p>
{% if user.is_authenticated %}
{% if user.author.id == author.id %}
<p><a href="{% url 'update-author' author.id %}">Edit this page</a></p>
{% endif %}
{% endif %}
{% endblock %}

blog/templates/blog/author_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Update your information</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update" />
</form>
{% endblock %}

blog/templates/blog/author_list.html
{% extends 'base.html' %}
{% block content %}
{% if author_list %}
<h1>Authors on this site:</h1>
<ul>
{% for author in author_list %}
<li><a href="{% url 'author-detail' author.pk %}">{{ author }}</a></li>
{% endfor %}
</ul>
{% else %}
<p><strong>There are no authors to print!</strong></p>
{% endif %}
{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add Comment" />
</form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
{% block content %}
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Title of a featured blog post</h1>
    <p class="lead my-3">The 'lede' of the featured blog post. Can support multiple lines of text, giving a teaser for the full post</p>
    <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        Latest
      </h3>
      
      {% for post in post_list %}
      <div class="blog-post">
        <h2 class="blog-post-title"><a href='{% url 'post-detail' post.pk %}'>{{ post.title }}</a></h2>
        <p class="blog-post-meta">{{ post.published.date }} by <a href="{% url 'author-detail' post.author.pk %}">{{ post.author.user.username }}</a></p>
        <p class="blog-text">{{ post.text }}</p>
      </div>
      {% endfor %}
      {% endblock %}
      {% block pagination %}
      {% if is_paginated %}
      <nav class="blog-pagination">
        {% if page_obj.has_next %}
        <a class="btn btn-outline-primary" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Older</a>
        {% else %}
        <a class="btn btn-outline-secondary" href="#">Older</a>
        {% endif %}
        {% if page_obj.has_previous %}
        <a class="btn btn-outline-primary" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Newer</a>
        {% else %}
        <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
        {% endif %}
      </nav>
      {% endif %}
      {% endblock %}
      
    </div>
    <aside class="col-md-4 blog-sidebar">
      <div class="p-3 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">This is a blog I'm making mostly to practice with Django, Bootstrap, etc.</p>
      </div>
    </aside>
  </div>
</main>
{% endblock %}
{% block footer %}
<footer class="blog-footer">
  <p>This blog was made by Matthew Ellis, this page is based off a template made by <a href="https://twitter.com/mdo">@mdo</a> for Bootstrap.</p>
<p><a href="#">Back to top</a></p>
      
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ post.title }}</h1>
<small>{{ post.published }} - <a href="{% url 'author-detail' post.author.id %}">{{ post.author }}</a></small>
<p>{{ post.text }}</p>
{% if user.is_authenticated %}
{% if user.author.id == post.author.id %}
<p><small><a href="{% url 'update-post' post.pk %} ">Edit this post</a></small></p>
{% endif %}
{% endif %}
<hr>
{% if post.comment_set.all %}
{% for comment in post.comment_set.all %}
<h4>{{ comment.title }}</h4>
<p>{{ comment.text }}</p>
<small>{{ comment.created }} - by {{ comment.user }}</small>
{% if comment.was_modified %}<p><small>(Comment edited {{ comment.last_modified }})</small></p>{% endif %}
{% endfor %}
<p><a href="{% url 'create-comment' post.id %}">Add a comment</a></p>
{% else %}
<p>There are no comments yet. Why not <a href="{% url 'create-comment' post.id %}">add one?</a></p>
{% endif %}

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Add a Post</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add Post" />
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Posts by {{ author }}</h1>
{% if author.post_set.all %}
{% for post in author.post_set.all %}
<h2><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
<p> {{ post.text }}</p>
<hr>
{% endfor %}
{% else %}
<h2>This author has no posts!</h2>
{% endif %}
{% endblock %}